DEFAULT_AMOUNT = 200000
DEFAULT_TERM_IN_MONTHS = 240
DEFAULT_INTEREST_RATE = 0.05
DEFAULT_INSTALLMENT_METHOD = 'fixed'

SIMULATION_HEADER = '  NR  DO SPŁATY    ODSETKI    KAPITAŁ       RATA'
SIMULATION_OUTPUT_FORMAT = '{:>4} {:>10.2f} {:>10.2f} {:>10.2f} {:>10.2f}'
SUMMARY_OUTPUT_FORMAT = 'Kwota kredytowana: {:.2f}\nKwota do wypłaty: {:.2f}\nSuma spłat: {:.2f}\n'
